version: '3.3'
services:
  app:
    image: galacticcouncil/forkwatch:latest
    environment:
      DATABASE_URL: postgresql://forkwatch:password@db:5432/forkwatch
      PORT: '3001'
      R: '1'
    networks:
      - net
      - gateway
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.forkwatch.rule: Host(`forkwatch.play.hydration.cloud`)
        traefik.http.routers.forkwatch.tls: 'true'
        traefik.http.routers.forkwatch.tls.certresolver: myresolver
        traefik.http.services.forkwatch.loadbalancer.server.port: '3001'
        swarmpit.service.deployment.autoredeploy: 'true'
      update_config:
        delay: 10s
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: forkwatch
      POSTGRES_PASSWORD: password
      POSTGRES_USER: forkwatch
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net
    logging:
      driver: json-file
networks:
  gateway:
    external: true
  net:
    driver: overlay
volumes:
  data:
    driver: local
