version: "3.8"

services:
  app:
    image: galacticcouncil/forkwatch:latest
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
      DATABASE_URL: "postgresql://forkwatch:password@db:5432/forkwatch"
      CHAINS: '[{"name":"polkadot","consensus":"babe","nodes":[{"name":"parity-rpc","url":"wss://rpc.polkadot.io"},{"name":"dwellir-rpc","url":"wss://polkadot-rpc.dwellir.com"},{"name":"ibp-rpc","url":"wss://rpc.ibp.network/polkadot"}],"knownAuthors":{}},{"name":"hydration","consensus":"aura","nodes":[{"name":"gc","url":"wss://rpc.hydradx.cloud"},{"name":"dwellir","url":"wss://hydration-rpc.n.dwellir.com"},{"name":"helikon","url":"wss://rpc.helikon.io/hydradx"},{"name":"dotters","url":"wss://hydration.dotters.network"},{"name":"ibp","url":"wss://hydration.ibp.network"},{"name":"parm","url":"wss://node.parm.hydration.cloud"},{"name":"roach","url":"wss://rpc.roach.hydration.cloud"},{"name":"zipp","url":"wss://rpc.zipp.hydration.cloud"},{"name":"sin","url":"wss://rpc.sin.hydration.cloud"},{"name":"coke","url":"wss://rpc.coke.hydration.cloud"},{"name":"lait","url":"wss://rpc.lait.hydration.cloud"},{"name":"stkd","url":"wss://hydration.rpc.stkd.io"}],"knownAuthors":{}},{"name":"moonbeam","consensus":"aura","nodes":[{"name":"moonbeam-foundation","url":"wss://wss.api.moonbeam.network"},{"name":"dwellir","url":"wss://moonbeam-rpc.dwellir.com"},{"name":"dotters","url":"wss://moonbeam.dotters.network"},{"name":"ibp","url":"wss://moonbeam.ibp.network"}],"knownAuthors":{}}]'
    networks:
      - net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "forkwatch"
      POSTGRES_USER: "forkwatch"
      POSTGRES_PASSWORD: "password"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

networks:
  net:

volumes:
  data:
